# Generated by Django 3.2.2 on 2021-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210426_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='contact',
            field=models.IntegerField(default=9999999999, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
